In [73]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [74]:
my_arr = np.arange(1000000)

In [75]:
my_list = list(range(1000000))

In [76]:
%timeit my_arr2 = my_arr * 2

533 µs ± 64.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [77]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 155 ms, sys: 46.4 ms, total: 201 ms
Wall time: 235 ms


In [78]:
data = np.random.randn(2, 3)

In [79]:
data

array([[ 0.60181623, -0.45442132, -0.53240586],
       [-0.5131169 , -0.32405405,  0.47870709]])

In [80]:
data * 10

array([[ 6.01816225, -4.54421319, -5.3240586 ],
       [-5.13116899, -3.24054053,  4.78707089]])

In [81]:
data + data

array([[ 1.20363245, -0.90884264, -1.06481172],
       [-1.0262338 , -0.64810811,  0.95741418]])

In [82]:
data = np.array([[1.5, -0.1,3], [0,-3, 6.5]])

In [83]:
daat

NameError: name 'daat' is not defined

In [84]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [85]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [86]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [87]:
data.shape

(2, 3)

In [88]:
data.dtype

dtype('float64')

In [89]:
data1 = [6, 7.5, 8, 0, 1]

In [90]:
arr1 = np.array(data1)

In [91]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [92]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [93]:
arr2 = np.array(data2)

In [94]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
arr2.ndim

2

In [96]:
arr2.shape

(2, 4)

In [97]:
arr1.dtype

dtype('float64')

In [98]:
arr2.dtype

dtype('int64')

In [99]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [101]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [102]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [103]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [104]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [105]:
arr1.dtype

dtype('float64')

In [106]:
arr2.dtype

dtype('int32')

In [107]:
arr = np.array([1, 2, 3, 4, 5])

In [108]:
arr.dtype

dtype('int64')

In [109]:
float_arr = arr.astype(np.float64)

In [110]:
float_arr

array([1., 2., 3., 4., 5.])

In [111]:
float_arr.dtype

dtype('float64')

In [112]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [113]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [114]:

arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [115]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype = np.string_)

In [116]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [117]:
int_array = np.arange(10)

In [118]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [119]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])