In [73]:
import numpy as np

# 4 NumPy Basics: Arrays and Vectorized Computation

In [74]:
my_arr = np.arange(1000000)

In [75]:
my_list = list(range(1000000))

In [76]:
%timeit my_arr2 = my_arr * 2

533 µs ± 64.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [77]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 155 ms, sys: 46.4 ms, total: 201 ms
Wall time: 235 ms


In [78]:
data = np.random.randn(2, 3)

In [79]:
data

array([[ 0.60181623, -0.45442132, -0.53240586],
       [-0.5131169 , -0.32405405,  0.47870709]])

In [80]:
data * 10

array([[ 6.01816225, -4.54421319, -5.3240586 ],
       [-5.13116899, -3.24054053,  4.78707089]])

In [81]:
data + data

array([[ 1.20363245, -0.90884264, -1.06481172],
       [-1.0262338 , -0.64810811,  0.95741418]])

In [82]:
data = np.array([[1.5, -0.1,3], [0,-3, 6.5]])

In [83]:
daat

NameError: name 'daat' is not defined

In [84]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [85]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [86]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [87]:
data.shape

(2, 3)

In [88]:
data.dtype

dtype('float64')

In [89]:
data1 = [6, 7.5, 8, 0, 1]

In [90]:
arr1 = np.array(data1)

In [91]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [92]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [93]:
arr2 = np.array(data2)

In [94]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
arr2.ndim

2

In [96]:
arr2.shape

(2, 4)

In [97]:
arr1.dtype

dtype('float64')

In [98]:
arr2.dtype

dtype('int64')

In [99]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [100]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [101]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [102]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [103]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [104]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [105]:
arr1.dtype

dtype('float64')

In [106]:
arr2.dtype

dtype('int32')

In [107]:
arr = np.array([1, 2, 3, 4, 5])

In [108]:
arr.dtype

dtype('int64')

In [109]:
float_arr = arr.astype(np.float64)

In [110]:
float_arr

array([1., 2., 3., 4., 5.])

In [111]:
float_arr.dtype

dtype('float64')

In [112]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [113]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [114]:

arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [115]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype = np.string_)

In [116]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [117]:
int_array = np.arange(10)

In [118]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [119]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [124]:
zeros_unit32


array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [126]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [127]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [128]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [129]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [130]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [131]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [133]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [134]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [135]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [136]:
arr = np.arange(10)

In [137]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
arr[5]

5

In [139]:
arr[5:8]

array([5, 6, 7])

In [140]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
arr_slice = arr[5:8]

In [142]:
arr_slice

array([5, 6, 7])

In [143]:
arr[5:8] = 12

In [144]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [145]:
arr_slice = arr[5:8]

In [146]:
arr_slice

array([12, 12, 12])

In [147]:
arr_slice[1] = 12345

In [148]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [149]:
arr_slice[:] = 64

In [150]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [152]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [153]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
arr2d[2]

array([7, 8, 9])

In [155]:
arr2d[0][2]

3

In [156]:
arr2d[0][1]

2

In [157]:
arr2d[0, 2]

3

In [166]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [167]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [172]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [173]:
old_values = arr3d[0].copy()

In [174]:
arr3d[0] = 42

In [175]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [176]:
arr3d[0] = old_values

In [177]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [178]:
arr3d[1, 0]

array([7, 8, 9])

In [179]:
x = arr3d[1]

In [180]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [181]:
x[0]

array([7, 8, 9])

In [182]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [183]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [184]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [185]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [186]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [187]:
lower_dim_slice = arr2d[1, :2]

In [188]:
lower_dim_slice

array([4, 5])

In [189]:
lower_dim_slice.shape

(2,)

In [191]:
arr2d[:2, 2]

array([3, 6])

In [192]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [193]:
arr2d[:2, 1:] = 0

In [194]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [197]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [198]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])

In [199]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [200]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [201]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [202]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [205]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [207]:
data[names == "Bob", :1]

array([[4],
       [0]])

In [209]:
data[names == "Bob", 1]

array([7, 0])

In [210]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [211]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [212]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [213]:
cond = names == "Bob"

In [214]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [215]:
mask = (names == "Bob") | (names == "Will")

In [216]:
mask

array([ True, False,  True,  True,  True, False, False])

In [217]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [218]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [219]:
data[data < 0] = 0

In [220]:
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [221]:
data[names != "Joe"] = 7

In [222]:
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

In [223]:
arr = np.zeros((8, 4))

In [224]:
for i in range (8):
    arr[i] = i

In [225]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [226]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [227]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [228]:
arr = np.arange(32).reshape((8, 4))

In [229]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [230]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [231]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [232]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0

In [233]:
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [234]:
arr = np.arange(15).reshape((3,5))

In [235]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [236]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [238]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])

In [239]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [240]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [241]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [242]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [243]:
arr.swapaxes(0,1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

In [244]:
samples = np.random.standard_normal(size =(4,4))

In [245]:
samples

array([[ 2.66678181,  0.28832055, -0.46018142,  1.65171992],
       [-0.22045445,  0.66835101,  1.53520682, -1.11347135],
       [ 1.41565229, -0.03631013,  0.09101151, -1.35047054],
       [ 1.0067157 , -0.74520716, -0.37537794,  1.73793017]])

In [246]:
from random import normalvariate

In [247]:
N = 1_000_000

In [248]:
 %timeit samples = [normalvariate(0, 1) for _ in range(N)]

338 ms ± 93.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [251]:
%timeit np.random.standard_normal(N)

13.6 ms ± 204 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [253]:
rng = np.random.default_rng(seed=12345)

In [254]:
data = rng.standard_normal((2, 3))

In [255]:
type(rng)

numpy.random._generator.Generator

In [256]:
arr = np.arange(10)

In [257]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [258]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [259]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [260]:
x = rng.standard_normal(8)

In [262]:
y = rng.standard_normal(8)

In [263]:
x

array([-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
        0.96849691, -0.75938718,  0.90219827])

In [264]:
y

array([-0.46695317, -0.06068952,  0.78884434, -1.25666813,  0.57585751,
        1.39897899,  1.32229806, -0.29969852])

In [265]:
np.maximum(x, y)

array([-0.46695317,  0.6488928 ,  0.78884434, -1.25666813,  2.34740965,
        1.39897899,  1.32229806,  0.90219827])

In [266]:
arr = rng.standard_normal(7) * 5

In [267]:
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [268]:
remainder, whole_part = np.modf(arr)

In [269]:
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [270]:
remainder

array([ 0.51459671, -0.10791367, -0.7909463 ,  0.24741966, -0.71800536,
       -0.40843795,  0.62369966])

In [271]:
whole_part

array([ 4., -8., -0.,  2., -6., -0.,  8.])

In [272]:
arr

array([ 4.51459671, -8.10791367, -0.7909463 ,  2.24741966, -6.71800536,
       -0.40843795,  8.62369966])

In [273]:
out = np.zeros_like(arr)

In [274]:
np.add(arr, 1)

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [275]:
np.add(arr, 1, out=out)

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])

In [276]:
out

array([ 5.51459671, -7.10791367,  0.2090537 ,  3.24741966, -5.71800536,
        0.59156205,  9.62369966])